name: FetalMRI_MONAI
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - numpy=1.23.1
  - pip=21.1.3
  - python=3.9.2
  - scikit-image=0.19.3
  - scipy=1.10.1
  - pytorch=2.0.1
  
  
  - pip:
    - monai
    - einops
    - nibabel
    - pandas
    - tqdm
    - torchvision
    
    

